import Anthropic from "@anthropic-ai/sdk";
import { kv } from "@vercel/kv";
import type { CommodityData, ShippingIndicator } from "@/types";

// ── Email renderer ────────────────────────────────────────────────────────────

export function briefToHtml(text: string, generatedAt: string): string {
  const dateStr = new Date(generatedAt).toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const body = text
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^## (.+)$/gm, '<h2 style="color:#ff8800;font-size:16px;margin:24px 0 8px;font-family:monospace;">$1</h2>')
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #2a2d3a;margin:20px 0;">')
    .replace(/^[-•] (.+)$/gm, '<li style="color:#cbd5e1;font-size:14px;line-height:1.6;margin:4px 0;">$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#f1f5f9;">$1</strong>')
    .replace(/^(?!<[hli]).+$/gm, (line) =>
      line.trim() ? `<p style="color:#cbd5e1;font-size:14px;line-height:1.6;margin:8px 0;">${line}</p>` : ""
    );

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="background:#0d0d0d;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:620px;margin:0 auto;padding:32px 24px;">
    <div style="border-bottom:1px solid #2a2d3a;padding-bottom:20px;margin-bottom:24px;">
      <div style="display:flex;align-items:baseline;gap:12px;margin-bottom:4px;">
        <span style="color:#eaeaea;font-size:20px;font-weight:900;letter-spacing:-0.5px;font-family:monospace;">TIBER</span>
        <span style="color:#ff8800;font-size:11px;font-family:monospace;letter-spacing:3px;">BRIEF</span>
      </div>
      <div style="color:#475569;font-size:11px;font-family:monospace;letter-spacing:2px;text-transform:uppercase;">
        Daily Procurement Intelligence · ${dateStr}
      </div>
    </div>
    <div>${body}</div>
    <div style="border-top:1px solid #2a2d3a;margin-top:32px;padding-top:16px;">
      <p style="color:#334155;font-size:11px;font-family:monospace;margin:0 0 8px;">
        Generated by Claude Sonnet 4.6 · Data: FRED / Federal Reserve · Not financial advice
      </p>
      <p style="color:#334155;font-size:11px;font-family:monospace;margin:0;">
        View live dashboard: <a href="https://pulse.tibermfg.com" style="color:#ff8800;">pulse.tibermfg.com</a>
        · <a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:#475569;">Unsubscribe</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

const client = new Anthropic();

const BRIEF_CACHE_KEY = "brief:v2"; // single JSON object { text, generatedAt }
const CACHE_TTL_SECONDS = 60 * 60 * 36; // 36h — survive a missed cron run

// ── Context builder ───────────────────────────────────────────────────────────

function formatTrend(pct: number): string {
  if (pct > 0) return `+${pct.toFixed(1)}% (↑ rising)`;
  if (pct < 0) return `${pct.toFixed(1)}% (↓ falling)`;
  return "flat";
}

function dataAge(frequency: "daily" | "monthly", lastUpdated: string): string {
  if (frequency === "daily") return `as of ${lastUpdated} (daily)`;
  // For monthly series, show the month the observation covers
  const d = new Date(lastUpdated);
  const month = d.toLocaleDateString("en-US", { month: "long", year: "numeric", timeZone: "UTC" });
  return `latest available: ${month} (monthly — may be 4–8 weeks old)`;
}

export function buildBriefContext(
  commodities: CommodityData[],
  shipping: ShippingIndicator[]
): string {
  const lines: string[] = [
    "=== RAW MATERIAL PRICES ===",
    "IMPORTANT: Monthly series reflect the most recently published period, which may be 4-8 weeks old. When writing about monthly data, always cite the observation period (e.g. 'February data shows...'), never imply it happened today or this week.",
    "",
  ];

  for (const c of commodities) {
    lines.push(
      `${c.name} (${c.symbol}): ${c.currentPrice.toFixed(2)} ${c.unit} — ${formatTrend(c.changePercent)} vs prior period | ${dataAge(c.frequency, c.lastUpdated)} | prior reading: ${c.priorPrice.toFixed(2)}`
    );
  }

  lines.push("");
  lines.push("=== SUPPLY CHAIN & LOGISTICS INDICATORS ===");

  for (const s of shipping) {
    let context = "";
    if (s.id === "inv_ratio") context = "(months of supply; rising = slack demand or improving supply)";
    if (s.id === "mfg_prod")  context = "(index 2017=100; rising = expanding output)";
    lines.push(
      `${s.name}: ${s.currentValue.toFixed(2)} ${s.unit} — ${formatTrend(s.changePercent)} vs prior period ${context} | latest available: ${s.lastUpdated} (monthly) | prior: ${s.priorValue.toFixed(2)}`
    );
  }

  return lines.join("\n");
}

// ── KV helpers ────────────────────────────────────────────────────────────────

export async function getCachedBrief(): Promise<{ text: string; generatedAt: string } | null> {
  try {
    const entry = await kv.get<{ text: string; generatedAt: string }>(BRIEF_CACHE_KEY);
    if (!entry?.text) {
      console.log("[brief] KV miss — no cached brief found");
      return null;
    }
    return entry;
  } catch (err) {
    console.error("[brief] KV read error:", err);
    return null;
  }
}

async function setCachedBrief(text: string, generatedAt: string): Promise<void> {
  try {
    await kv.set(BRIEF_CACHE_KEY, { text, generatedAt }, { ex: CACHE_TTL_SECONDS });
    console.log("[brief] KV write success — generatedAt:", generatedAt);
  } catch (err) {
    console.error("[brief] KV write error:", err);
    throw err; // re-throw so cron route sees the failure
  }
}

// ── Generation ────────────────────────────────────────────────────────────────

export async function generateAndCacheBrief(
  commodities: CommodityData[],
  shipping: ShippingIndicator[]
): Promise<string> {
  const context = buildBriefContext(commodities, shipping);
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const systemPrompt = `You are a senior supply chain analyst writing the daily "Tiber Brief" — a concise morning intelligence report for procurement managers, operations directors, and executives at US hardware and manufacturing companies.

Your audience buys raw materials (metals, energy) in volume. They are reading this first thing in the morning and need to know:
- What changed since the last reading and whether it matters
- Whether to act today — accelerate purchases, lock in contracts, or hold
- Any signals that suggest conditions are shifting

Tone: direct, data-driven, no fluff. Lead with what changed. Use exact price numbers from the data.`;

  const userPrompt = `Today is ${today}. Write the Tiber Brief based on the latest market data below.

Data freshness rules — follow these strictly:
- Daily series (crude oil): reference the specific date, changes are recent and can be framed as current
- Monthly series (metals, steel PPI, nat gas, indicators): always cite the observation period by name ("February data", "the January reading") — never write as if the change happened today or this week. A reader receiving this on March 27 should understand that a February data point is the most recent available, not a signal from this morning.

Call out moves that are material (>1% for daily, >2% for monthly). If a market is flat, say so briefly and move on.

Structure exactly as follows:

## 🏭 Market Pulse
2-3 sentences. What is the single most important development today? Overall condition: Stable / Cautious / Volatile. Be specific — name the commodity or indicator driving the call.

## 🔩 Materials Market
For each commodity with a notable move, 1-2 sentences: current price, change from prior reading, and what it means for a buyer today. Group flat/minor movers into one sentence. Always cite the actual numbers.

## 🚢 Logistics & Freight
2-3 sentences on diesel, inventory ratios, and manufacturing output. Flag any direction changes from prior readings.

## 📋 Today's Playbook
3-5 specific actions a procurement manager should consider today. Be direct: "Buy", "Hold", "Watch", "Lock in now", "Wait". Cite prices and the reason in one line each.

## ⚠️ Watch List
2-3 forward-looking signals to monitor. Short bullets only.

---

MARKET DATA (change labels indicate the comparison period):
${context}

Keep total brief to 400–550 words. Every claim should reference a number from the data.`;

  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 1500,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  });

  const text = response.content
    .filter((b) => b.type === "text")
    .map((b) => (b as { type: "text"; text: string }).text)
    .join("");

  const generatedAt = new Date().toISOString();
  await setCachedBrief(text, generatedAt);
  return text;
}
