import Anthropic from "@anthropic-ai/sdk";
import { kv } from "@vercel/kv";
import type { CommodityData, ShippingIndicator } from "@/types";

// ── Email renderer ────────────────────────────────────────────────────────────

export function briefToHtml(text: string, generatedAt: string): string {
  const dateStr = new Date(generatedAt).toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const body = text
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/^## (.+)$/gm, '<h2 style="color:#ff8800;font-size:16px;margin:24px 0 8px;font-family:monospace;">$1</h2>')
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #2a2d3a;margin:20px 0;">')
    .replace(/^[-•] (.+)$/gm, '<li style="color:#cbd5e1;font-size:14px;line-height:1.6;margin:4px 0;">$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#f1f5f9;">$1</strong>')
    .replace(/^(?!<[hli]).+$/gm, (line) =>
      line.trim() ? `<p style="color:#cbd5e1;font-size:14px;line-height:1.6;margin:8px 0;">${line}</p>` : ""
    );

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="background:#0d0d0d;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:620px;margin:0 auto;padding:32px 24px;">
    <div style="border-bottom:1px solid #2a2d3a;padding-bottom:20px;margin-bottom:24px;">
      <div style="display:flex;align-items:baseline;gap:12px;margin-bottom:4px;">
        <span style="color:#eaeaea;font-size:20px;font-weight:900;letter-spacing:-0.5px;font-family:monospace;">TIBER</span>
        <span style="color:#ff8800;font-size:11px;font-family:monospace;letter-spacing:3px;">BRIEF</span>
      </div>
      <div style="color:#475569;font-size:11px;font-family:monospace;letter-spacing:2px;text-transform:uppercase;">
        Daily Procurement Intelligence · ${dateStr}
      </div>
    </div>
    <div>${body}</div>
    <div style="border-top:1px solid #2a2d3a;margin-top:32px;padding-top:16px;">
      <p style="color:#334155;font-size:11px;font-family:monospace;margin:0 0 8px;">
        Generated by Claude Opus 4.6 · Data: FRED / Federal Reserve · Not financial advice
      </p>
      <p style="color:#334155;font-size:11px;font-family:monospace;margin:0;">
        View live dashboard: <a href="https://pulse.tibermfg.com" style="color:#ff8800;">pulse.tibermfg.com</a>
        · <a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:#475569;">Unsubscribe</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

const client = new Anthropic();

const BRIEF_CACHE_KEY = "brief:v2"; // single JSON object { text, generatedAt }
const CACHE_TTL_SECONDS = 60 * 60 * 36; // 36h — survive a missed cron run

// ── Context builder ───────────────────────────────────────────────────────────

function formatTrend(pct: number): string {
  if (pct > 0) return `+${pct.toFixed(1)}% (↑ rising)`;
  if (pct < 0) return `${pct.toFixed(1)}% (↓ falling)`;
  return "flat";
}

export function buildBriefContext(
  commodities: CommodityData[],
  shipping: ShippingIndicator[]
): string {
  const lines: string[] = [
    "=== RAW MATERIAL PRICES (latest period vs. prior period) ===",
  ];

  for (const c of commodities) {
    lines.push(
      `${c.name} (${c.symbol}): ${c.currentPrice.toFixed(2)} ${c.unit} — ${formatTrend(c.changePercent)} | as of ${c.lastUpdated}`
    );
  }

  lines.push("");
  lines.push("=== SUPPLY CHAIN & LOGISTICS INDICATORS ===");

  for (const s of shipping) {
    let context = "";
    if (s.id === "inv_ratio") {
      context = "(months of supply; rising = slower sales or better supply)";
    }
    lines.push(
      `${s.name}: ${s.currentValue.toFixed(1)} ${s.unit} — ${formatTrend(s.changePercent)} ${context} | as of ${s.lastUpdated}`
    );
  }

  return lines.join("\n");
}

// ── KV helpers ────────────────────────────────────────────────────────────────

export async function getCachedBrief(): Promise<{ text: string; generatedAt: string } | null> {
  try {
    const entry = await kv.get<{ text: string; generatedAt: string }>(BRIEF_CACHE_KEY);
    if (!entry?.text) return null;
    return entry;
  } catch {
    return null;
  }
}

async function setCachedBrief(text: string, generatedAt: string): Promise<void> {
  try {
    await kv.set(BRIEF_CACHE_KEY, { text, generatedAt }, { ex: CACHE_TTL_SECONDS });
  } catch {
    // KV not configured — skip silently
  }
}

// ── Generation ────────────────────────────────────────────────────────────────

export async function generateAndCacheBrief(
  commodities: CommodityData[],
  shipping: ShippingIndicator[]
): Promise<string> {
  const context = buildBriefContext(commodities, shipping);
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const systemPrompt = `You are a senior supply chain analyst who writes the daily "Tiber Brief" — a concise, authoritative market intelligence report for procurement managers, operations directors, and executives at domestic hardware and manufacturing companies.

Your audience buys raw materials (metals, plastics, energy) in volume. They care about:
- How price changes affect their COGS and margins
- Whether to accelerate purchases (buy ahead) or hold
- Supply chain disruptions, lead-time risks, and logistics costs
- Actionable intelligence they can act on this week

Tone: direct, professional, data-driven. No fluff. Use specific numbers.`;

  const userPrompt = `Today is ${today}. Write the daily Tiber Brief using the market data below.

Structure the brief exactly as follows (use these Markdown headers):

## 🏭 Market Pulse
2-3 sentence executive summary. Overall supply chain health this week (Stable / Cautious / Volatile). Single most important thing procurement managers need to know.

## 🔩 Materials Market
For each commodity with significant movement (>2% change), write 2-3 sentences: current price, direction, why it matters for manufacturers, and what to do. Group minor movers together in one sentence.

## 🚢 Logistics & Freight
2-3 sentences covering freight costs and supplier lead times. Flag any warning signs.

## 📋 Procurement Playbook
3-5 specific, actionable bullet points for this week. Examples: "Lock in Q2 copper contracts now — price climbing toward 12-month high" or "Hold steel inventory; PPI trending down."

## ⚠️ Watch List
2-3 items to monitor this week. Short bullets only.

---

MARKET DATA:
${context}

Keep the total brief to 450–650 words. Be specific — cite actual price numbers from the data.`;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const thinking = { type: "adaptive" } as any;

  const response = await client.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 1500,
    thinking,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  });

  const text = response.content
    .filter((b) => b.type === "text")
    .map((b) => (b as { type: "text"; text: string }).text)
    .join("");

  const generatedAt = new Date().toISOString();
  await setCachedBrief(text, generatedAt);
  return text;
}
